// <auto-generated />
namespace Emojo.Lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class follower_relationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(follower_relationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201612102122246_follower_relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
